name: Docker Image CI

on:
  push:
    branches:
      - main
    tags: 
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo "${{ github.ref }}"
